---
name: Build and Push Python app to AWS ECR
on: 
  push:
    branches: [ main ]
jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    steps:
    - name: Checkour
      uses: actions/checkout@v2
