---
name: Build and Push Python app to Docker
on: 
  push:
    branches: [ main ]
jobs:
  build-and-push:
    name: Build image
    runs-on: ubuntu-latest
    steps:
    - name: Checkour
      uses: actions/checkout@v2

    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: abzz786/demo-app
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}